name: Despliegue automático con Surge.sh

on:
  push:
    branches:
      - main  # Cambia a "master" si usas esa rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Surge.sh requiere Node.js

      - name: Instalar Surge.sh globalmente
        run: npm install -g surge

      - name: Desplegar con Surge.sh
        run: surge ./ --domain CSlorens1.surge.sh  # Cambia "tu-dominio" por uno único
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}  # Tu correo de Surge.sh
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Tu token de Surge.sh